
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/test?serverTimezone=GMT%2B8&charactorEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#  jpa:
#    show-sql: true
server:
  port: 8081


video:
  ffmpeg:
    path: ffmpeg
  ffprobe:
    path: ffprobe
  rtmp:
    prefix: rtmp://ip:1935/live/




